version: 2.1
description: A Net-Li-Fly Deploy Orb

orbs:
jobs:
  OF-build:
    docker:
      - image: circleci/node:10
    environment:
      NETLIFY_SITE_ID: NETLIFY_SITE_ID
      NETLIFY_ACCESS_TOKEN: A_NETLIFY_ACCESS_TOKEN
    working_directory: ~/repo
    steps:
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=public
  release:
    docker:
      - image: circleci/node:10
    environment:
      NETLIFY_SITE_ID: NETLIFY_SITE_ID
      NETLIFY_ACCESS_TOKEN: A_NETLIFY_ACCESS_TOKEN    
      working_directory: ~/repo
    steps:
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public