jobs:
  OF-build:
    executor: node-executor
    environment:
      NETLIFY_SITE_ID: NETLIFY_SITE_ID
      NETLIFY_ACCESS_TOKEN: A_NETLIFY_ACCESS_TOKEN
    working_directory: ~/repo
    steps:
      - gatsby-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=public
  release:
    executor: node-executor
    environment:
      NETLIFY_SITE_ID: YOUR_NETLIFY_SITE_ID
      NETLIFY_ACCESS_TOKEN: A_NETLIFY_ACCESS_TOKEN    
      working_directory: ~/repo
    steps:
      - gatsby-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public